2022-07-27 08:51:51,727 INFO    MainThread:2330734 [wandb_setup.py:_flush():76] Configure stats pid to 2330734
2022-07-27 08:51:51,727 INFO    MainThread:2330734 [wandb_setup.py:_flush():76] Loading settings from /root/.config/wandb/settings
2022-07-27 08:51:51,727 INFO    MainThread:2330734 [wandb_setup.py:_flush():76] Loading settings from /home/compu/jh/project/colon_compare/scripts/logs/evaluations/runs/default/2022-07-27_08-51-26/wandb/settings
2022-07-27 08:51:51,727 INFO    MainThread:2330734 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'_require_service': 'True'}
2022-07-27 08:51:51,727 WARNING MainThread:2330734 [wandb_setup.py:_flush():76] Could not find program at ../test.py
2022-07-27 08:51:51,727 INFO    MainThread:2330734 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': None, 'program': '../test.py'}
2022-07-27 08:51:51,728 INFO    MainThread:2330734 [wandb_init.py:_log_setup():461] Logging user logs to ./wandb/run-20220727_085151-2o4khaul/logs/debug.log
2022-07-27 08:51:51,728 INFO    MainThread:2330734 [wandb_init.py:_log_setup():462] Logging internal logs to ./wandb/run-20220727_085151-2o4khaul/logs/debug-internal.log
2022-07-27 08:51:51,728 INFO    MainThread:2330734 [wandb_init.py:init():495] calling init triggers
2022-07-27 08:51:51,728 INFO    MainThread:2330734 [wandb_init.py:init():498] wandb.init called with sweep_config: {}
config: {}
2022-07-27 08:51:51,728 INFO    MainThread:2330734 [wandb_init.py:init():548] starting backend
2022-07-27 08:51:51,728 INFO    MainThread:2330734 [wandb_init.py:init():552] setting up manager
2022-07-27 08:51:51,732 INFO    MainThread:2330734 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-07-27 08:51:51,734 INFO    MainThread:2330734 [wandb_init.py:init():558] backend started and connected
2022-07-27 08:51:51,746 INFO    MainThread:2330734 [wandb_init.py:init():634] updated telemetry
2022-07-27 08:51:51,889 INFO    MainThread:2330734 [wandb_init.py:init():665] communicating run to backend with 30 second timeout
2022-07-27 08:52:11,945 WARNING MsgRouterThr:2330734 [router.py:message_loop():76] message_loop has been closed
2022-07-27 08:52:21,891 INFO    MainThread:2330734 [interface_shared.py:_communicate_run():326] couldn't get run from backend
2022-07-27 08:52:21,892 ERROR   MainThread:2330734 [wandb_init.py:init():674] backend process timed out
2022-07-27 08:52:21,892 ERROR   MainThread:2330734 [wandb_init.py:init():685] encountered error: Error communicating with wandb process
try: wandb.init(settings=wandb.Settings(start_method='fork'))
or:  wandb.init(settings=wandb.Settings(start_method='thread'))
For more info see: https://docs.wandb.ai/library/init#init-start-error
