2022-08-17 10:39:57,392 INFO    MainThread:442237 [wandb_setup.py:_flush():76] Configure stats pid to 442237
2022-08-17 10:39:57,392 INFO    MainThread:442237 [wandb_setup.py:_flush():76] Loading settings from /root/.config/wandb/settings
2022-08-17 10:39:57,392 INFO    MainThread:442237 [wandb_setup.py:_flush():76] Loading settings from /home/compu/jh/project/colon_compare/scripts/logs/evaluations/runs/ubc/voting/2022-08-17_10-39-17/wandb/settings
2022-08-17 10:39:57,392 INFO    MainThread:442237 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'_require_service': 'True'}
2022-08-17 10:39:57,392 WARNING MainThread:442237 [wandb_setup.py:_flush():76] Could not find program at ../test.py
2022-08-17 10:39:57,392 INFO    MainThread:442237 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': None, 'program': '../test.py'}
2022-08-17 10:39:57,393 INFO    MainThread:442237 [wandb_init.py:_log_setup():461] Logging user logs to ./wandb/run-20220817_103957-20immstn/logs/debug.log
2022-08-17 10:39:57,393 INFO    MainThread:442237 [wandb_init.py:_log_setup():462] Logging internal logs to ./wandb/run-20220817_103957-20immstn/logs/debug-internal.log
2022-08-17 10:39:57,393 INFO    MainThread:442237 [wandb_init.py:init():495] calling init triggers
2022-08-17 10:39:57,393 INFO    MainThread:442237 [wandb_init.py:init():498] wandb.init called with sweep_config: {}
config: {}
2022-08-17 10:39:57,393 INFO    MainThread:442237 [wandb_init.py:init():548] starting backend
2022-08-17 10:39:57,393 INFO    MainThread:442237 [wandb_init.py:init():552] setting up manager
2022-08-17 10:39:57,395 INFO    MainThread:442237 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-08-17 10:39:57,402 INFO    MainThread:442237 [wandb_init.py:init():558] backend started and connected
2022-08-17 10:39:57,408 INFO    MainThread:442237 [wandb_init.py:init():636] updated telemetry
2022-08-17 10:39:57,537 INFO    MainThread:442237 [wandb_init.py:init():667] communicating run to backend with 30 second timeout
2022-08-17 10:40:27,538 INFO    MainThread:442237 [interface_shared.py:_communicate_run():331] couldn't get run from backend
2022-08-17 10:40:27,539 ERROR   MainThread:442237 [wandb_init.py:init():676] backend process timed out
2022-08-17 10:40:27,539 ERROR   MainThread:442237 [wandb_init.py:init():685] encountered error: Error communicating with wandb process
For more info see: https://docs.wandb.ai/library/init#init-start-error
2022-08-17 10:41:42,265 WARNING MsgRouterThr:442237 [router.py:message_loop():76] message_loop has been closed
